### ISSUE TITLE
It cant run in Xcode 6.3 ?

### ISSUE THREAD

**Issue by billjone** [pNre/ExSwift#105]
It cant run in Xcode 6.3 ?

**Comment by vmanot** [comment]
That's a pretty ... *informative* answer.

**Comment by pNre** [comment]
ExSwift works just fine in Xcode 6.3, follow the instructions in the README to add the library to your project.

**Comment by chrux** [comment]
In the README? the are not instructions.

**Comment by chrux** [comment]
If wanted https://github.com/pNre/ExSwift/pull/110

**Comment by mash** [comment]
+1
