### ISSUE TITLE
NSDate.addDays does not work on ios7

### ISSUE THREAD

**Issue by xinwo** [pNre/ExSwift#106]
change add to below works

    public func add(seconds: Int = 0, minutes: Int = 0, hours: Int = 0, days: Int = 0, weeks: Int = 0, months: Int = 0, years: Int = 0) -> NSDate {
        var calendar = NSCalendar.currentCalendar()
        let version = floor(NSFoundationVersionNumber)
        if ( version <= NSFoundationVersionNumber_iOS_7_1 || version <= NSFoundationVersionNumber10_9_2  ) {
            var component = NSDateComponents()
            component.second = seconds
            component.minute = minutes
            component.hour = hours
            component.day = days + weeks * 7
            component.month = months
            component.year = years
            return calendar.dateByAddingComponents(component, toDate: self, options: nil)!
        }
        
        var date : NSDate! = calendar.dateByAddingUnit(.CalendarUnitSecond, value: seconds, toDate: self, options: nil)
        date = calendar.dateByAddingUnit(.CalendarUnitMinute, value: minutes, toDate: date, options: nil)
        date = calendar.dateByAddingUnit(.CalendarUnitDay, value: days, toDate: date, options: nil)
        date = calendar.dateByAddingUnit(.CalendarUnitHour, value: hours, toDate: date, options: nil)
        date = calendar.dateByAddingUnit(.CalendarUnitWeekOfMonth, value: weeks, toDate: date, options: nil)
        date = calendar.dateByAddingUnit(.CalendarUnitMonth, value: months, toDate: date, options: nil)
        date = calendar.dateByAddingUnit(.CalendarUnitYear, value: years, toDate: date, options: nil)
        return date
    }

**Comment by PGLongo** [comment]
Why you say it doesn't work?

I have try this in the playground

```swift

public func add(seconds: Int = 0, minutes: Int = 0, hours: Int = 0, days: Int = 0, weeks: Int = 0, months: Int = 0, years: Int = 0) -> NSDate {

    var calendar = NSCalendar.currentCalendar()

        var component = NSDateComponents()
        component.second = seconds
        component.minute = minutes
        component.hour = hours
        component.day = days
        component.weekOfMonth = weeks
        component.month = months
        component.year = years
        return calendar.dateByAddingComponents(component, toDate: self, options: nil)!
    
    }
}

var date = NSDate()
println(date) // "2015-04-03 11:58:40 +0000"
var newDate  = date.add(seconds: 0, minutes: 0, hours: 0, days: 0, weeks: 1, months: 0, years: 0)
println(newDate) // "2015-04-10 11:58:40 +0000"
```

It seems working to me.

**Comment by PGLongo** [comment]
Ok I have found another possible mistake in the published version. The components .Hour and .Day must be reverted. I create a PR for that!

**Comment by xinwo** [comment]
can you tell me where the mistake is
I don't know why it isn't working now, I just found out that it is not.

**Comment by PGLongo** [comment]
Because operation on date are not commutative, the order you add the unit can produce different results.

**Comment by xinwo** [comment]
Thank you
