### ISSUE TITLE
Compile error caused by param mismatch for addMinutes method of NSDate

### ISSUE THREAD

**Issue by chainone** [pNre/ExSwift#117]
/**
        Returns a new NSDate object representing the date calculated by adding an amount of minutes to self date
    
        :param: minutes number of minutes to add
        :returns: the NSDate computed
    */
    public func addMinutes (minute: Int) -> NSDate {
        return add(minutes: minute)
    }

The parameter name declared in the comments (minutes) is different form that in the method declaration which would cause XCode to raise an error.

**Comment by pNre** [comment]
Which error is this causing?

**Comment by chainone** [comment]
thanks pNre!
