### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by sebastiaanluca** [pNre/ExSwift#141]
> 1. Add ExSwift as a submodule
> 2. Open the ExSwift project folder, and drag ExSwift sub folder with source code into the file navigator of your Xcode project. Make sure you select add to target
> 3. Use it

I dragged the ExSwift.xcodeproj file to my project, and then copied the ExSwift subfolder to my project directory, but it fails to build. I have no idea what's necessary to get this running as everything's explained quite cryptically.

**Comment by MrBendel** [comment]
You don't need to drag the xcodeproj to your project. All you need to do is add the source files and make sure they're targeted to your target.

**Comment by sebastiaanluca** [comment]
Ow lol, ok. Seems to work. The "Add ExSwift as a submodule" was kind of misleading. Thx ;$

**Comment by MrBendel** [comment]
@sebastiaanluca you can still add exswift as a submodule! Just add the repo as a submodule, but when adding to your project, just drag the source code in.
