### ISSUE TITLE
Issue with Ayn's fork

### ISSUE THREAD

**Issue by michaeleisel** [pNre/ExSwift#150]
@ayn thanks so much for creating a fork that works on later versions of Swift, but unfortunately I get lots of errors, like "availability has been replaced with available", any ideas?

**Comment by ayn** [comment]
Don't think `ExSwift` uses `@available` checks. Are you sure it's not from your own code? If you let us know which file(s) and line numbers you got the errors on it would help.

**Comment by michaeleisel** [comment]
See https://github.com/ayn/ExSwift/blob/master/ExSwift/String.swift and search for "availability"

**Comment by ayn** [comment]
Please use the swift 2 branch: https://github.com/ayn/ExSwift/blob/Swift-2.0/ExSwift/String.swift

**Comment by michaeleisel** [comment]
Thanks :)
