### ISSUE TITLE
Swift 3 vs ExSwift.swift

### ISSUE THREAD

**Issue by arodeus** [pNre/ExSwift#152]
**Swift3 tip, not a bug**

This code give operator warning: "operator should not be with body"

`infix operator =~ {}
infix operator |~ {}
infix operator .. {}
infix operator <=> {}`

Commenting/Removing brackets solve the warning.

**Comment by Esqarrouth** [comment]
A maintained repo: https://github.com/goktugyil/EZSwiftExtensions

**Comment by ankurp** [comment]
An alternative https://github.com/ankurp/Cent

**Comment by muescha** [comment]
is swift3 planned for this repo?

**Comment by pNre** [comment]
Sorry but no since I'm no longer able to maintain the repo.

**Comment by muescha** [comment]
ok thx for the info
