### ISSUE TITLE
ExSwift breaks range subscripting

### ISSUE THREAD

**Issue by itavor** [pNre/ExSwift#32]
The following code

```
let array1 = ["zero", "one", "two", "three"][1...3]
let array2 = ["zero", "one", "two", "three"][1..<3]
```

In a project which includes ExSwift results, for the first statement, in

```
'ClosedInterval<T>' is not convertible to 'Int'
```

And for the second statement:

```
'HalfOpenInterval<T>' is not convertible to 'Int'
```

In both cases the error marker points at the first dot in the subscript.

**Comment by ozgur** [comment]
@pNre why is this extension defined as internal?
