### ISSUE TITLE
Nil filter method on array

### ISSUE THREAD

**Issue by michaeleisel** [pNre/ExSwift#59]
Sometimes I want to, given an array of an optional type, return an array of the corresponding non-optional type, where all nil values have been filtered out. Here's my best attempt, but it doesn't compile: https://gist.github.com/michaeleisel/32f7e80ce2186f1edc95

Any ideas?

**Comment by nickmshelley** [comment]
Why not just mapFilter with the identity function?

**Comment by pNre** [comment]
You can't write an extension that only applies to an array of optionals. 
As @nickmshelley suggests, you can do:
```swift
array.mapFilter(mapFunction: { $0 })
```

**Comment by michaeleisel** [comment]
Yeah mapFilter was perfect, thanks
