### ISSUE TITLE
flatMap

### ISSUE THREAD

**Issue by hiltonc** [pNre/ExSwift#62]
I'm using `flatMap` in a project, would that be a generally useful thing to add to ExSwift?

    func flatMap<A, B>(x: A?, f: A -> B?) -> B? {
        if let value = x {
            return f(value)
        }
        return nil
    }

If so I can open a PR, just wanted to check since I'm not sure this matches the style of the rest of the extensions.

**Comment by pNre** [comment]
It's not that it doesn't match the style, but is this method really needed? Isn't it the same as doing:
```swift
let v = x == nil ? nil : f(x!)
```

**Comment by hiltonc** [comment]
A lot of the methods in ExSwift are the same as doing some one liner :). But yeah, it's pretty simple, and if it isn't often used there's certainly no need. Thanks!

**Comment by pNre** [comment]
It's true that some of the methods are simple but they also extend a type, here's why they're in the library :)
