### ISSUE TITLE
Support for Swift 1.2

### ISSUE THREAD

**Issue by Rhuantavan** [pNre/ExSwift#80]
Any plans to support the latest swift release?

**Comment by pizthewiz** [comment]
@markusl's PR #78 includes all the relevant changes for Swift 1.2 support and the tests pass as well. It would be great if this could at least be integrated as a branch if _master_ weren't ready to make the leap.

**Comment by pNre** [comment]
Support for Swift 1.2 is now available in the [Swift-1.2](https://github.com/pNre/ExSwift/tree/Swift-1.2) branch.
