### ISSUE TITLE
Please consider extending ExSwift to more areas

### ISSUE THREAD

**Issue by mike-lischke** [pNre/ExSwift#91]
I wonder if you have considered to include support classes that are not only related to data types in ExSwift. For instance code like the accepted answer at http://stackoverflow.com/questions/24581517/read-a-file-url-line-by-line-in-swift might be a good addition, starting a new ***file handling*** group of classes/functions.

**Comment by pNre** [comment]
Yes, I though about it and I decided to keep ExSwift the way it is.
This is because I don't want it to become a *"monster"* library extending every class in the ObjC/Swift runtime (that would also be a pain to maintain).
