### ISSUE TITLE
Naming issue

### ISSUE THREAD

**Issue by mike-lischke** [pNre/ExSwift#92]
ExSwift now contains some functions that contain the **Right** appendix (e.g. reduceRight) meaning to do a reverse operation compared to reduce. May I suggest to avoid the **Right** appendix and replace it by e.g. **Reverse** because **Right** has a strong connotation to writing directions (right-to-left vs left-to-right) which is not at all what these functions are about.

**Comment by pNre** [comment]
That might be a good idea for the `Swift-1.2/ExSwift 0.2` release, using **Reverse** sounds like a more swift-y naming standard.

**Comment by pNre** [comment]
`reduceRight` is deprecated (7955cbe6bf26be1b14e397022952a3b341665257) in favor of `reverse().reduce`.
